[package]
name = "post_infinity"
version = "5.3.0"
edition = "2024"

[workspace]

[dependencies]
binrw = "^0.14.1"
clap = { version = "^4.0", features = ["derive", "env"] }
env_logger = "^0.11.1"
log = "^0.4.22"
models = { path = "./models" }
serde_json = "^1.0"
